# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
url:              https://scorpion-css.github.io
baseurl:          ""
timezone: Australia/NSW
future: false

# gems:
#   - jekyll-redirect-from
#   - jekyll-sitemap

# Custom vars
description:      Scorpion.css is a beautifull, full feature, and simply awesome front-end css framework for building websites. It has been designed by @lucasgruwez, @arthur_guiot, and maintained by him and the awesome github comunity.
current-version:  1.0.0-alpha.7
code-license:     MIT License
docs-license:     creative commons license
repo:             https://github.com/Scorpion-css/framework
download:         https://github.com/Scorpion-css/framework.zip
cdn:              https://unpkg.com/scorpion.css/dist/css/scorpion.min.css

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: ""
      meta: ""
      categories: []
      tags: []
